services:
  performance_review_frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_APP_BASE_URL: ${NEXT_APP_BASE_URL}
    volumes:
      - performance:/app/
    restart: always
    ports:
      - "3050:3000" # map port 3030 to container's 3000 if needed
    networks:
      - performance_network

volumes:
  performance: # removed external:true

networks:
  performance_network: # removed external:true
